server {
    listen 8080
    root /home/tbeauman/Documents/42Projects/webserv/_siths/
}

server {
    listen 8081
    root /home/tbeauman/Documents/42Projects/webserv/_siths/post_malone
    index index.html
    autoindex on
    methods POST
    upload on
    upload_store /upload
    client_max_body_size 10000000000
    cgi on
    cgi_extension php sh py
    cgi_path /home/tbeauman/Documents/42Projects/webserv/_siths/shit_web/cgi-bin

}

server {
    listen 8420
    root /home/tbeauman/Documents/42Projects/webserv/_siths/shit_web
    index index.html
    autoindex on
    methods DELETE
    cgi on
    cgi_extension sh 
    cgi_path /home/tbeauman/Documents/42Projects/webserv/_siths/shit_web/cgi-bin
}

server {
    listen 8083
    root /home/tbeauman/Documents/42Projects/webserv/_siths/dark_maul
    index index.py

    cgi on
    cgi_extension php sh py
    cgi_path /home/tbeauman/Documents/42Projects/webserv/_siths/dark_maul/cgi-bin

}