server {
    listen 8080
    error_page 404 405 403 404.html
    server_name    test0
    root    ./site0
    index index.html
    location /  {
        root /var/www
        index index.html2
    }
}
server {
    listen 65200
    error_page 404 404.html
    server_name    test1
    root    ./site0
    cgi on
    cgi_path cgi
    cgi_extension py php sh
    index index.html
    location /oui/non  {
        root /var/www
        index index.html2
    }
    location /oui/non/peutetre  {
    }
}