server {
    listen 8080
    root /home/tbeauman/Documents/42Projects/webserv/assets
    index ziziprout.html
    cgi on
    cgi_extension php sh py
    cgi_path /home/tbeauman/Documents/42Projects/webserv/cgi_bin
    client_max_body_size 2000000

    location / {
        methods GET POST
    }
}
